FILEPATH_STOCK_PRICES: str = 'stock_prices.json'
FILEPATH_GURU_ARTICLES: str = 'guru_urls.json'
FOLDER_GURU_ARTICLES_BACKUP: str = 'articles_backup'
FILEPATH_GURU_SOURCES: str = 'guru_source.json'
FILEPATH_STOCK_CODES: str = 'hk_stocks.json'